create and pay, with a few type solving on purchase
LeroyMichael/PowerUp pull request #20
Opened 2024-07-06 03:56 UTC by DarrylEgbertNangoi-GitHub

Create:
https://jam.dev/c/92c315ed-c25f-4876-8d4a-440c9a9cc86c

Create and Pay: 
https://jam.dev/c/545352ae-109b-4a1d-849f-7794f1e24822

2024-07-06 11:23 UTC, LeroyMichael requested changes

2024-07-06 11:23 UTC, LeroyMichael commented on app/(protected)/expenses/[...expense]/components/ExpenseAddItemsTable.tsx
> +                          )}
https://github.com/LeroyMichael/PowerUp/blob/b243c3bb26fc7f1f5929a4050f95a1d5f396649e/app/(protected)/transactions/transaction-form/%5B%5B...transaction%5D%5D/page.tsx#L556-L565

perlu tambahin formatting ini dibwh pricenya supaya keliatan cth Rp100.000

2024-07-06 23:08 UTC, DarrylEgbertNangoi-GitHub commented on app/(protected)/expenses/[...expense]/components/ExpenseAddItemsTable.tsx
> +                          )}
updated

2024-07-08 13:02 UTC, LeroyMichael commented
![image](https://github.com/LeroyMichael/PowerUp/assets/58857692/252bef77-d825-4dd3-8215-281ecfe56652)
contactnya cba ikutin di page sales deh, jd klo mau update dia yg selected lansgung taro diatas

2024-07-08 13:15 UTC, LeroyMichael approved these changes
need some improvements for contact details
merging the existing code

2024-07-08 13:15 UTC, merged