feature: create Purchase UI
LeroyMichael/PowerUp pull request #4
Opened 2024-06-10 10:17 UTC by DarrylEgbertNangoi-GitHub

2024-06-19 15:23 UTC, LeroyMichael requested changes
Request fix/add
- add wallets (Select) | get data from getWallets
- tambah tax fields (tax_rate selalu percentage) show juga total fix taxnya brapa

Notes
- pas select contact nanti backgroundnya jd gray | contoh di transactions
- add items perlu default value 1 row kosong & tambahin subtotal di atas add new item

2024-06-24 14:49 UTC, LeroyMichael requested changes

2024-06-24 14:49 UTC, LeroyMichael commented on app/(protected)/purchases/[...purchase]/components/PurchaseCustomerDetails.tsx
> +          <ScrollArea className="h-[300px]">
perlu tambah search contact + logicnya 
[reference](https://github.com/LeroyMichael/PowerUp/blob/ef6cefb4a8cb625d06a26251a1ac5919f23818b4/app/(protected)/sales/%5B...sale%5D/contactDetail.tsx#L101)
di paling bawah ada paginationnya
![image](https://github.com/LeroyMichael/PowerUp/assets/58857692/223fba61-3ed0-4948-832f-49011d090a40)

2024-06-24 14:49 UTC, LeroyMichael commented on app/(protected)/purchases/[...purchase]/components/PurchaseSubtotal.tsx
> +              <span>Rp{numberFixedToString(watchForm.total)}</span>
ini numberfixedtostring ganti jadi 
`
<NumericFormat
                                value={watchForm.total}
                                displayType={"text"}
                                prefix={"Rp"}
                                allowNegative={false}
                                decimalSeparator={","}
                                thousandSeparator={"."}
                                fixedDecimalScale={true}
                              />
`

2024-06-24 14:49 UTC, LeroyMichael commented on app/(protected)/purchases/[...purchase]/components/PurchaseSubtotal.tsx
> +              <span>Rp{numberFixedToString(watchForm.total)}</span>
berlaku buat semua price value ya
![image](https://github.com/LeroyMichael/PowerUp/assets/58857692/43292044-8a65-49c2-9c5d-f2a7073062f5)

2024-06-25 17:48 UTC, DarrylEgbertNangoi-GitHub commented on app/(protected)/purchases/[...purchase]/components/PurchaseSubtotal.tsx
> +              <span>Rp{numberFixedToString(watchForm.total)}</span>
done, tapi hasilnya Rp2.000 gada ,00

2024-06-25 17:48 UTC, DarrylEgbertNangoi-GitHub commented on app/(protected)/purchases/[...purchase]/components/PurchaseCustomerDetails.tsx
> +          <ScrollArea className="h-[300px]">
done

2024-06-25 17:49 UTC, merged