Feature purchase integration
LeroyMichael/PowerUp pull request #9
Opened 2024-06-26 16:52 UTC by DarrylEgbertNangoi-GitHub

<img width="1512" alt="Screen Shot 2024-06-26 at 23 50 16" src="https://github.com/LeroyMichael/PowerUp/assets/80251611/ca4083fb-1cb7-4808-a0fb-a3a3af225460">

<img width="1512" alt="Screen Shot 2024-06-26 at 23 50 21" src="https://github.com/LeroyMichael/PowerUp/assets/80251611/83314859-7cbf-43af-a503-3ff6a2c134f8">

2024-06-29 08:59 UTC, LeroyMichael requested changes
![image](https://github.com/LeroyMichael/PowerUp/assets/58857692/88da4c97-210a-4ea3-af7d-2d425a220a5d)
pas ngubah items qty, totalnya ga langsung ke update

2024-06-29 09:03 UTC, LeroyMichael commented
![image](https://github.com/LeroyMichael/PowerUp/assets/58857692/6ae1c340-131f-4dd1-879f-db6d42ad8b3e)
add items kurang description

2024-06-29 09:08 UTC, LeroyMichael commented
kalau transactionnya udah active, pagenya ga bsa diedit
![WhatsApp Image 2024-06-28 at 16 35 53_6326f4d6](https://github.com/LeroyMichael/PowerUp/assets/58857692/47afbea4-8d82-4db9-a680-950ddfac3332)
pas submit kluar notif error ini

2024-06-29 09:13 UTC, LeroyMichael requested changes

2024-06-29 09:13 UTC, LeroyMichael commented on lib/contacts/utils.ts
> +    `${process.env.NEXT_PUBLIC_URL}/api/contacts?merchant_id=${merchant_id}&page=${currentPage}${searchParams}`,
ini hrsnya
`&page=${currentPage}&search=${searchParams}`

2024-06-30 08:47 UTC, DarrylEgbertNangoi-GitHub commented on lib/contacts/utils.ts
> +    `${process.env.NEXT_PUBLIC_URL}/api/contacts?merchant_id=${merchant_id}&page=${currentPage}${searchParams}`,
searchparams kan udh di set diatasnya  si res

2024-06-30 08:48 UTC, DarrylEgbertNangoi-GitHub commented on lib/contacts/utils.ts
> +    `${process.env.NEXT_PUBLIC_URL}/api/contacts?merchant_id=${merchant_id}&page=${currentPage}${searchParams}`,
<img width="544" alt="Screen Shot 2024-06-30 at 15 47 51" src="https://github.com/LeroyMichael/PowerUp/assets/80251611/fa25af76-8c38-42da-8666-31776c38ca82">

2024-06-30 12:14 UTC, merged